GET http://localhost:3001/vehicle_types HTTP/1.1
content-type: application/json

{
}
###
GET http://localhost:3001/routes?type=2 HTTP/1.1
content-type: application/json

{
	"type" : 1
}
###
GET http://localhost:3001/stops HTTP/1.1
content-type: application/json

{
}

###
GET http://localhost:3001/path?route=67 HTTP/1.1
content-type: application/json

{
	"route" : "67"
}
###