GET http://localhost:3001/vehicle_types HTTP/1.1
content-type: application/json

{
}
###
GET http://localhost:3001/routes?type=2 HTTP/1.1
content-type: application/json

{
	"type" : 1
}
###
GET http://localhost:3001/stops HTTP/1.1
content-type: application/json

{
}

###
GET http://localhost:3001/departures?route=67 HTTP/1.1
content-type: application/json

{
	"route" : "67"
}
###

GET http://localhost:3001/arrivals HTTP/1.1
content-type: application/json

{
	"stop" : "Szent János tér",
	"hour" : 9,
	"direction" : 1
}

###

GET http://localhost:3001/routeexists HTTP/1.1
content-type: application/json

{
	"route" : "732"
}

###


GET http://localhost:3001/compatiblestops HTTP/1.1
content-type: application/json

{
	"route" : "2"
}

###