INSERT INTO megallo (cim, megallonev) VALUES
('Odessza, Temesvári körút, Fő fasor (Temesvári körút)','Fő fasor (Temesvári körút)'),
('Belváros, Tisza Lajos körút, Aradi vértanúk tere','Aradi vértanúk tere'),
('Belváros, Boldogasszony sugárút, Bécsi körút','Bécsi körút'),
('Újrókus, Harmónia lakópark, Rókusi körút, Szatymazi utca','Szatymazi utca'),
('Belváros, Tisza Lajos körút, Glattfelder Gyula tér','Glattfelder Gyula tér'),
('Kiskundorozsma, Széchenyi István utca, Basahíd utca','Basahíd utca'),
('Északi városrész, Gedó, Csongrádi sugárút, Diófa Vendéglő','Diófa Vendéglő'),
('Marostő, Hársfa lakópark, Fülemüle utca, Pipiske utca','Pipiske utca'),
('Tarján, Gedó, József Attila sugárút, Tarján','Tarján'),
('Felsőváros, Felső Tisza part, Etelka sor','Etelka sor'),
('Újrókus, Harmónia lakópark, Rókusi körút, Rókusi víztorony','Rókusi víztorony'),
('Móraváros, Kálvária sugárút, II. Kórház','II. Kórház'),
('Rókus, Harmónia lakópark, Kossuth Lajos sugárút, Vásárhelyi Pál utca','Vásárhelyi Pál utca'),
('Iparváros, Dorozsmai út, Tassi ház','Tassi ház'),
('Móraváros, Petőfi Sándor sugárút, Moszkvai körút','Moszkvai körút'),
('Kiskundorozsma, Dorozsmai út, ABC, Kiskundorozsma','Kiskundorozsma, ABC'),
('Rókus, Franciahögy lakópark, Szent Rókus tér, Mars tér (Szent Rókus tér)','Mars tér (Szent Rókus tér)'),
('Béketelep, Liliom lakókert, Csallóközi utca','Csallóközi utca'),
('Újpetőfitelep, Nagyszilléri domb, Hangos utca, Acél utca','Acél utca'),
('Alsóváros, Hattyas utca, Szabad sajtó utca','Szabad sajtó utca'),
('Alsóváros, Indóház tér, Szeged vasútállomás','Szeged vasútállomás'),
('Belváros, Aradi vértanúk tere','Aradi vértanúk tere'),
('Újpetőfitelep, Nagyszilléri domb, Algyői út, Szélső sor','Szélső sor'),
('Béketelep, Liliom lakókert, Régi posta út, Nagyszombati utca (páratlan oldal)','Nagyszombati utca (páratlan oldal)'),
('Béketelep, Pulz utca, Szeged Plaza','Szeged Plaza'),
('Subasa, Széksósi út, Csipkebogyó utca, Subasa','Subasa, Csipkebogyó utca'),
('Tápé, Tömörkény-üdülőtelep, Budai Nagy Antal utca, Beszterce utca','Beszterce utca'),
('Újszőreg, Kállayliget, Makai út, Napfény köz','Napfény köz'),
('Kiskundorozsma, Dobos utca, Huszka Jenő utca','Huszka Jenő utca'),
('Tápé, Tömörkény-üdülőtelep, Bencfahát utca, Zágráb utca','Zágráb utca'),
('Tarján, Gedó, Budapesti körút, Csillag tér (Budapesti körút)','Csillag tér (Budapesti körút)'),
('Kiskundorozsma, Czékus utca, Erdőstarcsa utca','Erdőstarcsa utca'),
('Móraváros, Bécsi körút, Petőfi Sándor sugárút','Petőfi Sándor sugárút'),
('Felsőváros, Római körút, Sajka utca','Sajka utca'),
('Szentmihály, Bodom, Kapisztrán út, Gárdonyi Géza utca','Gárdonyi Géza utca'),
('Tarján, Gedó, Rózsa utca, Rózsa utca (József Attila sugárút)','Rózsa utca (József Attila sugárút)'),
('Baktó, Alkotmány utca, Kokárda utca','Kokárda utca'),
('Felsőváros, Brüsszeli körút, Sándor utca','Sándor utca'),
('Tápé, Budai Nagy Antal utca, Árok utca','Árok utca'),
('Alsóváros, Gólya utca','Gólya utca'),
('Szőreg, Szerb utca, Szőregi szabadidőpark','Szőregi szabadidőpark'),
('Belváros, Széchenyi tér','Széchenyi tér'),
('Tápé, Tömörkény-üdülőtelep, Bencfahát utca, Dráva utca','Dráva utca'),
('Móraváros, Kálvária sugárút, Veres ács utca','Veres ács utca'),
('Újszeged, Temesvári körút, Szent-Györgyi Albert utca','Szent-Györgyi Albert utca'),
('Szőreg, Magyar utca, Iskola utca','Iskola utca'),
('Iparváros, Fonógyári út, Fonógyári úti iparváros','Fonógyári úti iparváros'),
('Újrókus, Rókusi körút, Kisteleki utca','Kisteleki utca'),
('Makkosház, Gedó, Makkosházi körút, Agyagos utca','Agyagos utca'),
('Tarján, Gedó, Retek utca, József Attila sugárút (Retek utca)','József Attila sugárút (Retek utca)'),
('Kiskundorozsma, Jerney utca, Jerney János Általános Iskola','Jerney János Általános Iskola'),
('Tápé, Árvácska utca, általános iskola, Tápé','Tápé, általános iskola'),
('Iparváros, Tűzoltó utca','Tűzoltó utca'),
('Fodorkert, Gedó, Tölgyes utca, Budapesti körút','Budapesti körút'),
('Odessza, Népkert sor, Napfényfürdő','Napfényfürdő'),
('Kecskés István-telep, Terehalmi út, Bódi Vera utca, Kecskéstelep','Kecskéstelep, Bódi Vera utca'),
('Szentmihály, Szabadkai út, Szegedi Olimpiai Központ','Szegedi Olimpiai Központ'),
('Cserőke, Hársfa lakópark, Katalin utca, Klára utca','Klára utca'),
('Újpetőfitelep, Ladvánszky utca, Alkotmány utca','Alkotmány utca'),
('Gyálarét, Gyálaréti út, Apály utca','Apály utca'),
('Petőfitelep, Tömörkény-üdülőtelep, Irinyi János utca, Duna utca','Duna utca'),
('Szentmihály, Kapisztrán út, Verbéna utca','Verbéna utca'),
('Iparváros, Zápor út, Auchan parkoló','Auchan áruház'),
('Északi városrész, Gedó, Csongrádi sugárút, Rózsa utca (Csongrádi sugárút)','Rózsa utca (Csongrádi sugárút)'),
('Baktó, Völgyérhát utca','Völgyérhát utca'),
('Iparváros, Dorozsmai út, Kiskundorozsma vasútállomás','Kiskundorozsma vasútállomás'),
('Újszeged, Bérkert utca, Szöri utca','Szöri utca'),
('Kiskundorozsma, Széchenyi István utca, Szent János tér','Szent János tér'),
('Kiskundorozsma, Dorozsmai út, Csatorna','Csatorna'),
('Marostő, Hársfa lakópark, Fő fasor, Cinke utca','Cinke utca'),
('Újpetőfitelep, Délceg utca, Balatoni utca','Balatoni utca'),
('Belváros, Kossuth Lajos sugárút, Anna-kút (Kossuth Lajos sugárút)','Anna-kút (Kossuth Lajos sugárút)'),
('Belváros, Szent István tér','Szent István tér'),
('Budapesti út, Kísérleti gazdaság','Kísérleti gazdaság'),
('Tápé, Honfoglalás utca','Honfoglalás utca'),
('Rókus, Vásárhelyi Pál utca, Csemegi-tó','Csemegi-tó'),
('Petőfitelep, Szántó Kovács János utca, Fő tér, Petőfitelep','Petőfitelep, Fő tér'),
('Szőreg, Szerb utca, malom, Szőreg','Szőreg, malom'),
('Odessza, Lövölde út, Füvészkert','Füvészkert'),
('Odessza, Körsétaút, Napfényfürdő','Napfényfürdő'),
('Szentmihály, Bodom, Kapisztrán út, Artézi kút','Artézi kút'),
('Iparváros, Dorozsmai út, Budapesti út','Budapesti út'),
('Gyálarét, Gyálaréti út, Deli Károly utca','Deli Károly utca'),
('Tompasziget, Gyálai út, Kiskertek','Kiskertek'),
('Makkosház, Gedó, Ortutay utca, Gát utca','Gát utca'),
('Felsőváros, Római körút, Gál utca','Gál utca'),
('Kiskundorozsma, Kettőshatári út, vásártér, Kiskundorozsma','Kiskundorozsma, vásártér'),
('Makkosház, Harmónia lakópark, Csongrádi sugárút, Makkosházi körút (Csongrádi sugárút)','Makkosházi körút (Csongrádi sugárút)'),
('Iparváros, Bajai út, Repülőtér bejárati út','Repülőtér bejárati út'),
('Szentmihály, Bodom, Kapisztrán út, Koppány köz','Koppány köz'),
('Iparváros, Budapesti út, Zápor út','Zápor út'),
('Kecskés István-telep, Terehalmi út, Fehérparti lejáró','Fehérparti lejáró'),
('Tápé, Tömörkény-üdülőtelep, Kölcsey tér, általános iskola, Tápé','Tápé, általános iskola'),
('Alsóváros, Bem utca','Bem utca'),
('Fodorkert, Gedó, Budapesti körút, Budapesti körút (József Attila sugárút)','Budapesti körút (József Attila sugárút)'),
('Belváros, Franciahögy lakópark, Osztrovszky utca, Szent György tér','Szent György tér'),
('Belváros, Tisza Lajos körút, Déli Klinikai Tömb','Klinikák'),
('Rókus, Vásárhelyi Pál utca','Vásárhelyi Pál utca'),
('Iparváros, Fonógyári út, Kereskedő köz','Kereskedő köz'),
('Odessza, Torontál tér, Torontál tér (P+R)','Torontál tér (P+R)'),
('Szőreg, Gőzmalom utca','Gőzmalom utca'),
('Újszeged, Hársfa lakópark, Derkovits fasor, Diófa utca (Derkovits fasor)','Diófa utca (Derkovits fasor)'),
('Iparváros, Tűzoltó utca, Első Szegedi Ipari Park','Első Szegedi Ipari Park'),
('Móraváros, Katona József utca, Alkony utca','Alkony utca'),
('Felsőváros, Felső Tisza part, Tabán utca (Felső Tisza-part)','Tabán utca (Felső Tisza-part)'),
('Nádvágó út, Fehértói halgazdaság','Fehértói halgazdaság'),
('Felsőváros, Szilléri sugárút, Fecske utca','Fecske utca'),
('Iparváros, Bakay Nándor utca','Bakay Nándor utca'),
('Felsőváros, József Attila sugárút, Dankó Pista utca','Dankó Pista utca'),
('Móraváros, Katona József utca, Szél utca','Szél utca'),
('Lövölde út, Füvészkert','Füvészkert'),
('Odessza, Népkert sor, Temesvári körút (Népkert sor)','Temesvári körút (Népkert sor)'),
('Felsőváros, Gedó, Szilléri sugárút, Fecske utca','Fecske utca'),
('Béketelep, Zsámbokréti sor, MEDIKÉMIA, Béketelep','Béketelep, MEDIKÉMIA'),
('Szegedi Ipari Logisztikai Központ, Back Bernát utca, Back Bernát utca 2.','Back Bernát utca 2.'),
('Odessza, Vedres utca, Torontál tér (P+R)','Torontál tér (P+R)'),
('Újrókus, Harmónia lakópark, Rókusi körút, Rókusi II. sz. általános iskola','Rókusi II. sz. általános iskola'),
('Odessza, 43303, Gyermekkórház','Gyermekkórház'),
('Móraváros, Moszkvai körút, Kálvária sugárút','Kálvária sugárút'),
('Kiskundorozsma, Szent János tér','Szent János tér'),
('Budapesti út, buszforduló, Gumigyár','Gumigyár, buszforduló'),
('Kiskundorozsma, Széksósi út, Brassói utca','Brassói utca'),
('Fodorkert, Gedó, József Attila sugárút, Budapesti körút','Budapesti körút'),
('Tarján, Gedó, Budapesti körút, víztorony, Tarján','Tarján, víztorony'),
('Újrókus, Harmónia lakópark, Körtöltés utca','Körtöltés utca'),
('Belváros, Mars tér, Mars tér (Attila utca)','Mars tér (Attila utca)'),
('Móraváros, Gólya utca, Kolozsvári tér','Kolozsvári tér'),
('Szentmihály, Bodom, Kapisztrán út, malom, Szentmihály','Szentmihály, malom'),
('Baktó, Alkotmány utca, Gyümölcs utca','Gyümölcs utca'),
('Petőfitelep, Nagyszilléri domb, Gyémánt utca, Lidicei tér','Lidicei tér'),
('Kiskundorozsma, Jerney utca, Malom (Jerney utca)','Malom (Jerney utca)'),
('Északi városrész, Gedó, Rózsa utca, Rózsa utca (Csongrádi sugárút)','Rózsa utca (Csongrádi sugárút)'),
('Móraváros, Kálvária sugárút, Kálvária tér','Kálvária tér'),
('Iparváros, Kereskedő köz, Kereskedelmi raktárak','Kereskedelmi raktárak'),
('Belváros, Híd utca, Széchenyi tér','Széchenyi tér'),
('Belváros, Kelemen László utca, Somogyi utca','Somogyi utca'),
('Fodorkert, Gedó, Makkosházi körút, Agyagos utca','Agyagos utca'),
('Béketelep, Liliom lakókert, Zsámbokréti sor','Zsámbokréti sor'),
('Béketelep, Liliom lakókert, Nagyszombati utca, Rengey utca','Rengey utca'),
('Rókus, Vásárhelyi Pál utca, Vásárhelyi Pál utca (Pulcz utca)','Vásárhelyi Pál utca (Pulcz utca)'),
('Magyarország, 6800, Alföld és Észak, Dél-Alföld, Csongrád-Csanád megye, Hódmezővásárhelyi járás, Hódmezővásárhely, Susán, Vízház utca, Hódmezővásárhely vasútállomás','Hódmezővásárhely vasútállomás'),
('Újszőreg, Kállayliget, Szőregi út, Kamaratöltés','Kamaratöltés'),
('Újszőreg, Kállayliget, Makai út, Kamaratöltés','Kamaratöltés'),
('Északi városrész, Harmónia lakópark, Rókusi körút, Makkosházi körút (Rókusi körút)','Makkosházi körút (Rókusi körút)'),
('Makkosház, Harmónia lakópark, Csongrádi sugárút, Ipoly sor','Ipoly sor'),
('Belváros, Boldogasszony sugárút, Galamb utca','Galamb utca'),
('Odessza, Vedres utca, Gabonakutató','Gabonakutató'),
('Iparváros, Bajai út, Krematórium','Krematórium'),
('Alsóváros, Szentháromság utca, Bécsi körút','Bécsi körút'),
('Makkosház, Gedó, Csongrádi sugárút, Makkosházi körút (Csongrádi sugárút)','Makkosházi körút (Csongrádi sugárút)'),
('Gyálarét, Gyálaréti kiskertek, Koszorú utca, Gyálarét','Gyálarét'),
('Felsőváros, Tömörkény-üdülőtelep, Felső Tisza part, Etelka sor','Etelka sor'),
('Felsőváros, József Attila sugárút, Brüsszeli körút','Brüsszeli körút'),
('Marostő, Hársfa lakópark, Fő fasor, Thököly utca','Thököly utca'),
('Odessza, Temesvári körút, Sportcsarnok (Temesvári körút)','Sportcsarnok (Temesvári körút)'),
('Alsóváros, Rákóczi utca, Szent Ferenc utca','Szent Ferenc utca'),
('Móraváros, Vadaspark lakópark, Katona József utca, Cserepes sor (Katona József utca)','Cserepes sor (Katona József utca)'),
('Rókus, Pulz utca','Pulz utca'),
('Magyarország, 6800, Alföld és Észak, Dél-Alföld, Csongrád-Csanád megye, Hódmezővásárhelyi járás, Hódmezővásárhely, Kertváros, Kisállomás sor, Hódmezővásárhelyi Népkert vasútállomás','Hódmezővásárhelyi Népkert vasútállomás'),
('Újszeged, Fő fasor, víztorony, Újszeged','Újszeged, víztorony'),
('Klebelsbergtelep, Vaskapu utca, Holt-Tisza','Holt-Tisza'),
('Makkosház, Csongrádi sugárút, Ipoly sor','Ipoly sor'),
('Klebelsbergtelep, Ballagitó, Pancsovai utca, Kamarási utca','Kamarási utca'),
('Felsőváros, Tömörkény-üdülőtelep, Felső Tisza part, Városi stadion','Városi stadion'),
('Iparváros, Kollégiumi út, Vállalkozó köz','Vállalkozó köz'),
('Makkosház, Gedó, Hont Ferenc utca, Gát utca','Gát utca'),
('Északi városrész, Franciahögy lakópark, Csongrádi sugárút, Tündér utca','Tündér utca'),
('Kecskés István-telep, Vadaspark lakópark, Szabadkai út, Gera Sándor utca, Kecskéstelep','Kecskéstelep, Gera Sándor utca'),
('Belváros, Földváry utca, Honvéd tér','Honvéd tér'),
('Makkosház, Gedó, Ortutay utca','Ortutay utca'),
('Alsóváros, Szabadkai út','Szabadkai út'),
('Kiskundorozsma, Széksósi út','Széksósi út'),
('Tarján, Gedó, Víztorony tér, Víztorony tér, Tarján','Tarján, Víztorony tér'),
('Kiskundorozsma, Negyvennyolcas utca, Balajthy utca','Balajthy utca'),
('Odessza, Székely sor, Sportcsarnok (Székely sor)','Sportcsarnok (Székely sor)'),
('Alsóváros, Petőfi Sándor sugárút, Rákóczi utca (Vám tér)','Rákóczi utca (Vám tér)'),
('Fodorkert, Gedó, József Attila sugárút, Deák Ferenc Gimnázium','Deák Ferenc Gimnázium'),
('Wolfgang Sandner utca, ELI lézeres kutatóközpont','ELI lézeres kutatóközpont'),
('Újszeged, Derkovits fasor, Töltés utca','Töltés utca'),
('Felsőváros, Felső Tisza part, Háló utca','Háló utca'),
('Móraváros, Bakay Nándor utca, Bakay Nándor utca (Vásárhelyi Pál utca)','Bakay Nándor utca (Vásárhelyi Pál utca)'),
('Gyálarét, Gyálaréti kiskertek, Koszorú utca','Koszorú utca'),
('Tarján, Gedó, József Attila sugárút, Retek utca','Retek utca'),
('Belváros, Tisza Lajos körút, Centrum Áruház','Centrum Áruház'),
('Móraváros, Petőfi Sándor sugárút, Szivárvány kitérő','Szivárvány kitérő'),
('Iparváros, Fonógyári út, Belvárosi temető','Belvárosi temető'),
('Marostő, Hársfa lakópark, Thököly utca, Erdélyi tér','Erdélyi tér'),
('Petőfitelep, Nagyszilléri domb, Csap utca','Csap utca'),
('Alsóváros, Sárkány utca','Sárkány utca'),
('Alsóváros, Vadaspark lakópark, Szabadkai út','Szabadkai út'),
('Marostő, Hársfa lakópark, Hargitai utca','Hargitai utca'),
('Tápé, Honfoglalás utca, Csatár utca','Csatár utca'),
('Belváros, Mikszáth Kálmán utca, Mars tér (Mikszáth Kálmán utca)','Mars tér (Mikszáth Kálmán utca)'),
('Északi városrész, Harmónia lakópark, Rókusi körút, Vértó','Vértó'),
('Móraváros, Bakay Nándor utca, Mura utca','Mura utca'),
('Belváros, Kálvin tér, Anna-kút (Kálvin tér)','Anna-kút (Kálvin tér)'),
('Béketelep, Napos út, Napos út (Dorozsmai út)','Napos út (Dorozsmai út)'),
('Belváros, Dózsa utca','Dózsa utca'),
('Móraváros, Kálvária sugárút, Londoni körút (Kálvária sugárút)','Londoni körút (Kálvária sugárút)'),
('Béketelep, Pulz utca, Rókus vasútállomás','Rókus vasútállomás'),
('Belváros, Kálvária sugárút, Londoni körút (Kálvária sugárút)','Londoni körút (Kálvária sugárút)'),
('Felsőváros, Hajós utca','Hajós utca'),
('Felsőváros, Szilléri sugárút, Római körút (Szilléri sugárút)','Római körút (Szilléri sugárút)'),
('Alsóváros, Szabadság tér','Szabadság tér'),
('Móraváros, Kenyérgyári út, Kenyérgyári út 5.','Kenyérgyári út 5.'),
('Újszeged, Hársfa lakópark, Szőregi út, Aranyosi utca','Aranyosi utca'),
('Móraváros, Vásárhelyi Pál utca, Kenyérgyári út','Kenyérgyári út'),
('Iparváros, Budapesti út, Budapesti út (Dorozsmai út)','Budapesti út (Dorozsmai út)'),
('Belváros, Tisza Lajos körút, Anna-kút (Tisza Lajos körút)','Anna-kút (Tisza Lajos körút)'),
('Iparváros, Textilgyári út, Vadaspark (Textilgyári út)','Vadaspark (Textilgyári út)'),
('Újszőreg, Kállayliget, Makai út, Kavics utca','Kavics utca'),
('Iparváros, Bajai út, Repülőtér','Repülőtér'),
('Rókus, Franciahögy lakópark, Kossuth Lajos sugárút, Damjanich utca','Damjanich utca'),
('Felsőváros, Etelka sor','Etelka sor'),
('Back Bernát utca, Szegedi Ipari Logisztikai Központ','Szegedi Ipari Logisztikai Központ'),
('Szőreg, Szerb utca, Rózsatő utca (Szerb utca)','Rózsatő utca (Szerb utca)'),
('Iparváros, Kollégiumi út, Fonógyári út (Kollégiumi út)','Fonógyári út (Kollégiumi út)'),
('Kecskés István-telep, Terehalmi út, Verbéna utca','Verbéna utca'),
('Kiskundorozsma, Dorozsmai út, Malom (Jerney utca)','Malom (Jerney utca)'),
('Marostő, Hársfa lakópark, Tanács utca, Thököly utca','Thököly utca'),
('Felsőváros, Gyík utca, Lugas utca','Lugas utca'),
('Budapesti út, Gumigyár (Budapesti út)','Gumigyár (Budapesti út)'),
('Alsóváros, Földmíves utca, Dobó utca','Dobó utca'),
('Újrókus, Harmónia lakópark, Rókusi körút, Rókus II. sz. általános iskola','Rókus II. sz. általános iskola'),
('Tarján, Gedó, József Attila sugárút, Kecskeméti utca','Kecskeméti utca'),
('Kiskundorozsma, Kút utca, Széchenyi István utca','Széchenyi István utca'),
('Subasa, Széksósi út, Subasa, Szeged','Szeged, Subasa'),
('Odessza, Alsó kikötő sor, Hatházak','Hatházak'),
('Szőreg, Magyar utca, Rózsatő utca (Magyar utca)','Rózsatő utca (Magyar utca)'),
('Újpetőfitelep, Délceg utca','Délceg utca'),
('Klebelsbergtelep, Rendező tér','Rendező tér'),
('Újszeged, Fő fasor','Fő fasor'),
('Felsőváros, Tömörkény-üdülőtelep, Felső Tisza part, Tabán utca (Felső Tisza-part)','Tabán utca (Felső Tisza-part)'),
('Belváros, Tisza Lajos körút, Honvéd tér (Tisza Lajos körút)','Honvéd tér (Tisza Lajos körút)'),
('Iparváros, Dorozsmai út, Fonógyári út','Fonógyári út'),
('Alsóváros, Vám tér','Vám tér'),
('Alsóváros, Csonka utca','Csonka utca'),
('Újszeged, Bérkert utca, Szövetség utca','Szövetség utca'),
('Rókus, Rókusi körút, Vásárhelyi Pál utca','Vásárhelyi Pál utca'),
('Újrókus, Vértói út','Vértói út'),
('Belváros, Stefánia, Múzeum','Múzeum'),
('Odessza, Lövölde út, Akácfa utca','Akácfa utca'),
('Iparváros, Fonógyári út, Ikarusz köz','Ikarusz köz'),
('Iparváros, Fonógyári út, Belvárosi temető II. kapu','Belvárosi temető II. kapu'),
('Újpetőfitelep, Nagyszilléri domb, Végvári utca, Acél utca','Acél utca'),
('Gyálarét, Gyálaréti kiskertek, Gyálaréti út, Koszorú utca','Koszorú utca'),
('Belváros, Kálvária sugárút, Dugonics tér (Dáni utca)','Dugonics tér (Dáni utca)'),
('Iparváros, Fonógyári út','Fonógyári út'),
('Béketelep, Napos út, Béketelepi Általános Iskola','Béketelepi Általános Iskola'),
('Móraváros, Kálvária sugárút, Földhivatal','Földhivatal'),
('Alsóváros, Vadkerti tér','Vadkerti tér'),
('Tompasziget, Gyálai út, Cincér utca','Cincér utca'),
('Belváros, Bartók tér','Bartók tér'),
('Belváros, Tisza Lajos körút, Dugonics tér (Petőfi Sándor sugárút)','Dugonics tér (Petőfi Sándor sugárút)'),
('Kiskundorozsma, Czékus utca','Czékus utca'),
('Marostői kiskertek, Hősök tere, ABC, Szőreg','Szőreg, ABC'),
('Újrókus, Kossuth Lajos sugárút, bejárati út, Szeged-Rókus vasútállomás','Szeged-Rókus vasútállomás, bejárati út'),
('Tápé, Honfoglalás utca, Rév utca','Rév utca'),
('Felsőváros, Brüsszeli körút','Brüsszeli körút'),
('Móraváros, Vásárhelyi Pál utca, Volánbusz Zrt.','Volánbusz Zrt.'),
('Móraváros, Londoni körút, Kálvária sugárút','Kálvária sugárút'),
('Belváros, Franciahögy lakópark, Berlini körút','Berlini körút'),
('Magyarország, 6800, Alföld és Észak, Dél-Alföld, Csongrád-Csanád megye, Hódmezővásárhelyi járás, Hódmezővásárhely, Kertváros, Ady Endre utca, Strandfürdő','Strandfürdő'),
('Újpetőfitelep, Nagyszilléri domb, Bánk bán utca, Kalász utca','Kalász utca'),
('Belváros, Mars tér, Mars tér (autóbusz-állomás)','Mars tér (autóbusz-állomás)'),
('Szőreg, Szerb utca, Gyár utca (Szerb utca)','Gyár utca (Szerb utca)'),
('Béketelep, Liliom lakókert, Régi posta út, Nagyszombati utca (páros oldal)','Nagyszombati utca (páros oldal)'),
('Iparváros, Bajai út','Bajai út'),
('Szőreg, Szerb utca, Kossuth Lajos Általános Iskola','Kossuth Lajos Általános Iskola'),
('Petőfitelep, Nagyszilléri domb, Csap utca, Gábor Áron utca','Gábor Áron utca'),
('Móraváros, Kálvária sugárút, Londoni körút','Londoni körút'),
('Újszeged, Bérkert utca, Marostői utca','Marostői utca'),
('Marostő, Hársfa lakópark, Derkovits fasor','Derkovits fasor'),
('Tápé, Budai Nagy Antal utca, Rév utca','Rév utca'),
('Móraváros, Bakay Nándor utca, Huszár utca','Huszár utca'),
('Petőfitelep, Szántó Kovács János utca, Zágráb utca','Zágráb utca'),
('Magyarország, 6750, Alföld és Észak, Dél-Alföld, Csongrád-Csanád megye, Szegedi járás, Algyő, Tanya utca, Algyő','Algyő'),
('Petőfitelep, Nagyszilléri domb, Gábor Áron utca','Gábor Áron utca'),
('Magyarország, 6800, Alföld és Észak, Dél-Alföld, Csongrád-Csanád megye, Hódmezővásárhelyi járás, Hódmezővásárhely, Belváros, Tóalj utca, Hősök tere','Hősök tere'),
('Odessza, Derkovits fasor, Kisstadion','Kisstadion'),
('Magyarország, 6800, Alföld és Észak, Dél-Alföld, Csongrád-Csanád megye, Hódmezővásárhelyi járás, Hódmezővásárhely, Hódtó, Andrássy út, Kálvin János tér','Kálvin János tér'),
('Tompasziget, Gyálai út, Szúnyog utca','Szúnyog utca'),
('Belváros, József Attila sugárút, Szent György tér','Szent György tér'),
('Klebelsbergtelep, Vadaspark lakópark, Horgosi utca, Kecskés','Kecskés'),
('Baktó, Alkotmány utca, Bognár utca','Bognár utca'),
('Rókus, Franciahögy lakópark, Kossuth Lajos sugárút, Tavasz utca','Tavasz utca'),
('Alsóváros, Vadaspark lakópark, Cserepes sor','Cserepes sor'),
('Móraváros, Katona József utca, Hajnal utca','Hajnal utca'),
('Cserőke, Katalin utca','Katalin utca'),
('Iparváros, Kollégiumi út, Dorozsmai út (Kollégiumi út)','Dorozsmai út (Kollégiumi út)'),
('Sziksós, Turista utca, Sziksósfürdő','Sziksósfürdő'),
('Móraváros, Vásárhelyi Pál utca, Kálvária sugárút (Vásárhelyi Pál utca)','Kálvária sugárút (Vásárhelyi Pál utca)'),
('Rókus, Mars tér, Mars tér (üzletsor)','Mars tér (üzletsor)'),
('Belváros, Tisza Lajos körút, Tisza Lajos körút (Károlyi utca)','Tisza Lajos körút (Károlyi utca)'),
('Alsóváros, Rákóczi utca, Rákóczi utca (Vám tér)','Rákóczi utca (Vám tér)'),
('Iparváros, Kálvária sugárút, Vadaspark','Vadaspark'),
('Újszeged, Bérkert utca, Közép fasor (Bérkert utca)','Közép fasor (Bérkert utca)'),
('Iparváros, Dorozsmai út, Kollégiumi út','Kollégiumi út'),
('Makkosház, Ipoly sor, Makkosház','Makkosház'),
('Szegedi Ipari Logisztikai Központ, Back Bernát utca, Back Bernát utca 6.','Back Bernát utca 6.'),
('Tarján, Gedó, Retek utca, Szamos utca','Szamos utca'),
('Alsóváros, Tompai kapu út, buszforduló, Vadkerti tér','Vadkerti tér, buszforduló'),
('Magyarország, 6800, Alföld és Észak, Dél-Alföld, Csongrád-Csanád megye, Hódmezővásárhelyi járás, Hódmezővásárhely, Belváros, Andrássy út, Kossuth tér','Kossuth tér'),
('Béketelep, Liliom lakókert, Csallóközi utca, Rengey utca','Rengey utca'),
('Kecskés István-telep, Vadaspark lakópark, Szabadkai út, Bódi Vera utca, Kecskéstelep','Kecskéstelep, Bódi Vera utca'),
('Belváros, Ady tér, Vitéz utca','Vitéz utca'),
('Szentmihály, Bodom, Harcos utca','Harcos utca'),
('Belváros, Franciahögy lakópark, Csongrádi sugárút, Csongrádi sugárút (Bercsényi utca)','Csongrádi sugárút (Bercsényi utca)'),
('Újpetőfitelep, Nagyszilléri domb, Algyői út, Diadal utca','Diadal utca'),
('Belváros, Szentháromság utca, Ságvári Gimnázium - SZTK','Ságvári Gimnázium - SZTK'),
('Alsóváros, Szentháromság utca, Szent Ferenc utca','Szent Ferenc utca'),
('Móraváros, Petőfi Sándor sugárút, Vitéz utca','Vitéz utca'),
('Alsóváros, Sárkány utca, Vadkerti tér','Vadkerti tér'),
('Béketelep, Napos út, Cserje sor','Cserje sor'),
('Belváros, Dugonics tér, Dugonics tér (Kálvária sugárút)','Dugonics tér (Kálvária sugárút)'),
('Belváros, Mikszáth Kálmán utca, Centrum Áruház','Centrum Áruház'),
('Belváros, József Attila sugárút, Lengyel utca','Lengyel utca'),
('Újszeged, Hársfa lakópark, Derkovits fasor, Töltés utca','Töltés utca'),
('Marostő, Hársfa lakópark, Thököly utca, Traktor utca','Traktor utca'),
('Belváros, Franciahögy lakópark, Brüsszeli körút, Berlini körút','Berlini körút'),
('Északi városrész, Franciahögy lakópark, Csongrádi sugárút, Rózsa utca (Csongrádi sugárút)','Rózsa utca (Csongrádi sugárút)'),
('Szőreg, Magyar utca, Gyár utca (Magyar utca)','Gyár utca (Magyar utca)'),
('Makkosház, Harmónia lakópark, Csongrádi sugárút, Európa liget','Európa liget'),
('Tápé, Árvácska utca, Nyilassy utca','Nyilassy utca'),
('Újszeged, Töltés utca, víztorony, Újszeged','Újszeged, víztorony'),
('Odessza, Csanádi utca','Csanádi utca'),
('Belváros, Tisza Lajos körút, Dugonics tér (Tisza Lajos körút)','Dugonics tér (Tisza Lajos körút)'),
('Marostő, Hársfa lakópark, Tanács utca','Tanács utca'),
('Móraváros, Bakay Nándor utca, Londoni körút (Bakay Nándor utca)','Londoni körút (Bakay Nándor utca)'),
('Belváros, Attila utca, Bartók tér','Bartók tér'),
('Rókus, Franciahögy lakópark, Kossuth Lajos sugárút, Rókusi templom','Rókusi templom'),
('Újszeged, Fő fasor, Közép fasor','Közép fasor'),
('Makkosház, Gedó, Makkosházi körút','Makkosházi körút'),
('Belváros, Petőfi Sándor sugárút, Földváry utca','Földváry utca'),
('Alsóváros, Vadaspark lakópark, Szabadkai út, Szalámigyár','Szalámigyár'),
('Tompasziget, Gyálai út, Tücsök utca','Tücsök utca'),
('Iparváros, Kereskedő köz, Kereskedő köz (EXPO)','Kereskedő köz (EXPO)'),
('Tarján, Nagyszilléri domb, Algyői út, Szélső sor','Szélső sor'),
('Szőreg, Magyar utca, Vaspálya utca','Vaspálya utca'),
('Újrókus, Rókusi körút, Szatymazi utca','Szatymazi utca'),
('Odessza, Alsó kikötő sor','Alsó kikötő sor'),
('Felsőváros, Római körút, Római körút (Szilléri sugárút)','Római körút (Szilléri sugárút)'),
('Marostő, Hársfa lakópark, Fő fasor, Radnóti utca','Radnóti utca'),
('Északi városrész, Franciahögy lakópark, Csongrádi sugárút, Gém utca','Gém utca'),
('Belváros, Vörösmarty utca, Széchenyi tér (Horváth Mihály utca)','Széchenyi tér (Horváth Mihály utca)'),
('Rókus, Franciahögy lakópark, Párizsi körút, Hétvezér utca','Hétvezér utca'),
('Újszőreg, Makai út, Barázda utca','Barázda utca'),
('Kecskés István-telep, Vadaspark lakópark, Szabadkai út, Kecskés','Kecskés'),
('Odessza, Kállayliget, Szőregi út, Diófa utca (Szőregi út)','Diófa utca (Szőregi út)'),
('Odessza, Székely sor, Torontál tér (P+R)','Torontál tér (P+R)'),
('Tarján, Nagyszilléri domb, Lidicei tér','Lidicei tér'),
('Budapesti út, Öthalmi diáklakások','Öthalmi diáklakások'),
('Marostő, Hársfa lakópark, Hargitai utca, Pinty utca','Pinty utca'),
('Marostő, Bérkert utca, Tanács utca','Tanács utca'),
('Petőfitelep, Fő tér, Fő tér, Petőfitelep','Petőfitelep, Fő tér'),
('Felsőváros, Kereszttöltés utca, Csaba utca','Csaba utca'),
('Kiskundorozsma, Negyvennyolcas utca','Negyvennyolcas utca'),
('Felsőváros, Lugas utca, Csillag tér (Lugas utca)','Csillag tér (Lugas utca)'),
('Belváros, Attila utca, Attila utca (Mars tér)','Attila utca (Mars tér)'),
('Felsőváros, Etelka sor, Erdő utca','Erdő utca');