INSERT INTO befogad (megallo, jarmutipus) VALUES
('Glattfelder Gyula tér','2'),
('Kecskeméti utca','2'),
('Iskola utca','1'),
('Fonógyári út','2'),
('Délceg utca','1'),
('Radnóti utca','1'),
('Dugonics tér (Kálvária sugárút)','2'),
('Londoni körút (Kálvária sugárút)','1'),
('Töltés utca','1'),
('Sándor utca','1'),
('Földváry utca','1'),
('Kálvin János tér','2'),
('Kamarási utca','1'),
('Zápor út','1'),
('Szent-Györgyi Albert utca','1'),
('Vállalkozó köz','1'),
('Csaba utca','3'),
('Verbéna utca','1'),
('Körtöltés utca','3'),
('Rókusi víztorony','3'),
('Lengyel utca','1'),
('Rákóczi utca (Vám tér)','1'),
('Bécsi körút','1'),
('Rózsa utca (József Attila sugárút)','2'),
('Tavasz utca','2'),
('Tisza Lajos körút (Károlyi utca)','3'),
('Szeged vasútállomás','2'),
('Zsámbokréti sor','1'),
('Harcos utca','1'),
('Ortutay utca','3'),
('Római körút (Szilléri sugárút)','1'),
('Rókusi II. sz. általános iskola','3'),
('Szamos utca','1'),
('Gém utca','1'),
('Repülőtér bejárati út','1'),
('Bognár utca','1'),
('Fehérparti lejáró','1'),
('Dózsa utca','3'),
('Aranyosi utca','1'),
('Kossuth Lajos Általános Iskola','1'),
('Szöri utca','1'),
('Csanádi utca','1'),
('Szőreg, ABC','1'),
('Zágráb utca','1'),
('Diófa utca (Szőregi út)','1'),
('Tarján, víztorony','1'),
('Makkosházi körút (Csongrádi sugárút)','3'),
('Vásárhelyi Pál utca','2'),
('Centrum Áruház','3'),
('Kálvária sugárút','1'),
('Tanács utca','1'),
('Vaspálya utca','1'),
('Mars tér (autóbusz-állomás)','1'),
('Hódmezővásárhely vasútállomás','2'),
('Mars tér (autóbusz-állomás)','3'),
('Gyár utca (Szerb utca)','1'),
('Kavics utca','1'),
('Béketelep, MEDIKÉMIA','1'),
('Anna-kút (Kossuth Lajos sugárút)','2'),
('Sándor utca','3'),
('Budapesti út','1'),
('Dugonics tér (Dáni utca)','1'),
('Barázda utca','1'),
('Rókusi II. sz. általános iskola','1'),
('Bartók tér','3'),
('Koppány köz','1'),
('Makkosházi körút (Csongrádi sugárút)','1'),
('Füvészkert','1'),
('Dugonics tér (Tisza Lajos körút)','1'),
('Rókus II. sz. általános iskola','2'),
('Fonógyári út (Kollégiumi út)','1'),
('Kossuth tér','2'),
('Szőregi szabadidőpark','1'),
('Diófa utca (Derkovits fasor)','1'),
('Erdő utca','3'),
('Hősök tere','2'),
('Vásárhelyi Pál utca','1'),
('Rózsa utca (Csongrádi sugárút)','1'),
('Csaba utca','1'),
('Sárkány utca','1'),
('Anna-kút (Kálvin tér)','3'),
('Dugonics tér (Petőfi Sándor sugárút)','3'),
('Tabán utca (Felső Tisza-part)','1'),
('Anna-kút (Tisza Lajos körút)','3'),
('Fő fasor (Temesvári körút)','1'),
('Fecske utca','1'),
('Római körút (Szilléri sugárút)','3'),
('Cserepes sor','1'),
('Szabad sajtó utca','1'),
('Kiskundorozsma, ABC','1'),
('Kiskertek','1'),
('Lugas utca','3'),
('Gál utca','3'),
('Kiskundorozsma vasútállomás','1'),
('Kenyérgyári út','1'),
('Honvéd tér (Tisza Lajos körút)','3'),
('Széchenyi István utca','1'),
('Tarján','2'),
('Makkosház','1'),
('Kenyérgyári út 5.','1'),
('Tabán utca (Felső Tisza-part)','3'),
('Rengey utca','1'),
('Etelka sor','3'),
('Kecskéstelep, Bódi Vera utca','1'),
('Szabadkai út','1'),
('Veres ács utca','2'),
('Ipoly sor','1'),
('Cserepes sor (Katona József utca)','1'),
('Vám tér','2'),
('Szeged, Subasa','1'),
('Rókusi templom','2'),
('Kálvária tér','1'),
('Somogyi utca','2'),
('Kísérleti gazdaság','1'),
('Európa liget','2'),
('Repülőtér','1'),
('Budapesti út (Dorozsmai út)','1'),
('Diófa Vendéglő','3'),
('Napos út (Dorozsmai út)','1'),
('Basahíd utca','1'),
('Rókusi templom','1'),
('Kisstadion','1'),
('Derkovits fasor','1'),
('Tápé, általános iskola','1'),
('Anna-kút (Tisza Lajos körút)','1'),
('Vadaspark','2'),
('Hódmezővásárhelyi Népkert vasútállomás','2'),
('Vértó','1'),
('Makkosház','3'),
('Szövetség utca','1'),
('Hétvezér utca','3'),
('Csonka utca','1'),
('Múzeum','3'),
('Csatár utca','1'),
('Dorozsmai út (Kollégiumi út)','1'),
('Kecskéstelep, Gera Sándor utca','1'),
('Vadkerti tér','1'),
('Vadkerti tér, buszforduló','1'),
('Makkosházi körút (Rókusi körút)','1'),
('Ságvári Gimnázium - SZTK','1'),
('Moszkvai körút','1'),
('Deák Ferenc Gimnázium','2'),
('Aradi vértanúk tere','3'),
('Dugonics tér (Tisza Lajos körút)','2'),
('Erdélyi tér','1'),
('Gőzmalom utca','1'),
('Petőfi Sándor sugárút','1'),
('Kokárda utca','1'),
('Katalin utca','1'),
('Marostői utca','1'),
('Berlini körút','3'),
('Tücsök utca','1'),
('Fonógyári út','1'),
('Szent János tér','1'),
('Napfényfürdő','1'),
('Vértó','3'),
('Traktor utca','1'),
('Balajthy utca','1'),
('Dugonics tér (Petőfi Sándor sugárút)','1'),
('Kamaratöltés','1'),
('Béketelepi Általános Iskola','1'),
('Londoni körút (Bakay Nándor utca)','3'),
('Tisza Lajos körút (Károlyi utca)','2'),
('Kereskedő köz (EXPO)','1'),
('Gál utca','1'),
('Belvárosi temető','2'),
('Csillag tér (Lugas utca)','3'),
('Kalász utca','1'),
('Alkotmány utca','1'),
('Gát utca','1'),
('Rókus vasútállomás','2'),
('Torontál tér (P+R)','3'),
('Gárdonyi Géza utca','1'),
('Földhivatal','1'),
('Rév utca','1'),
('Brassói utca','1'),
('Glattfelder Gyula tér','1'),
('Árok utca','1'),
('Huszka Jenő utca','1'),
('Hétvezér utca','1'),
('Kereskedelmi raktárak','1'),
('Alkony utca','1'),
('Makkosházi körút (Rókusi körút)','3'),
('II. Kórház','2'),
('Gumigyár, buszforduló','1'),
('Lidicei tér','1'),
('Hatházak','1'),
('Rózsa utca (Csongrádi sugárút)','3'),
('Tavasz utca','1'),
('Fehértói halgazdaság','1'),
('Vértó','2'),
('Szent Ferenc utca','1'),
('Cserje sor','1'),
('Deák Ferenc Gimnázium','1'),
('Ikarusz köz','1'),
('Gumigyár (Budapesti út)','1'),
('Volánbusz Zrt.','1'),
('Szabadság tér','1'),
('Vértói út','3'),
('Bakay Nándor utca','3'),
('Rendező tér','1'),
('Völgyérhát utca','1'),
('Nyilassy utca','1'),
('Holt-Tisza','1'),
('Damjanich utca','2'),
('Honfoglalás utca','1'),
('Huszár utca','3'),
('Alsó kikötő sor','1'),
('Bartók tér','1'),
('Széchenyi tér','2'),
('Artézi kút','1'),
('Gyálarét','1'),
('Kisteleki utca','1'),
('Kollégiumi út','1'),
('Pipiske utca','1'),
('Subasa, Csipkebogyó utca','1'),
('Csemegi-tó','1'),
('Algyő','2'),
('Szegedi Ipari Logisztikai Központ','1'),
('Tassi ház','1'),
('Szeged vasútállomás','1'),
('Fő fasor','1'),
('Mars tér (üzletsor)','1'),
('Berlini körút','1'),
('Dugonics tér (Tisza Lajos körút)','3'),
('II. Kórház','1'),
('Centrum Áruház','1'),
('József Attila sugárút (Retek utca)','1'),
('Csap utca','1'),
('Ságvári Gimnázium - SZTK','3'),
('Klinikák','3'),
('Honvéd tér (Tisza Lajos körút)','1'),
('Rókusi víztorony','1'),
('Mars tér (Mikszáth Kálmán utca)','1'),
('Thököly utca','1'),
('Sportcsarnok (Székely sor)','1'),
('Duna utca','1'),
('Gyümölcs utca','1'),
('Budapesti körút','2'),
('Ortutay utca','1'),
('Vásárhelyi Pál utca (Pulcz utca)','1'),
('Fonógyári úti iparváros','1'),
('Brüsszeli körút','2'),
('Petőfitelep, Fő tér','1'),
('Torontál tér (P+R)','1'),
('Szabadkai út','2'),
('Széchenyi tér','3'),
('Napfény köz','1'),
('Vitéz utca','2'),
('Aradi vértanúk tere','2'),
('Öthalmi diáklakások','1'),
('Vértói út','1'),
('Szent György tér','2'),
('Széksósi út','1'),
('Diadal utca','1'),
('Dráva utca','1'),
('Tarján, Víztorony tér','3'),
('Jerney János Általános Iskola','1'),
('Beszterce utca','1'),
('Dobó utca','1'),
('Galamb utca','2'),
('Damjanich utca','1'),
('Mura utca','3'),
('Első Szegedi Ipari Park','1'),
('Csillag tér (Budapesti körút)','1'),
('Háló utca','3'),
('Gyár utca (Magyar utca)','1'),
('Gabonakutató','1'),
('Szent István tér','3'),
('Csanádi utca','3'),
('Malom (Jerney utca)','1'),
('Vadaspark','1'),
('Bem utca','2'),
('Agyagos utca','1'),
('Kiskundorozsma, vásártér','1'),
('Back Bernát utca 6.','1'),
('Makkosházi körút','3'),
('Sziksósfürdő','1'),
('Szentmihály, malom','1'),
('Akácfa utca','1'),
('Belvárosi temető','1'),
('Csatorna','1'),
('Szeged-Rókus vasútállomás, bejárati út','1'),
('Negyvennyolcas utca','1'),
('Szél utca','1'),
('Kálvária sugárút (Vásárhelyi Pál utca)','1'),
('Pulz utca','2'),
('Városi stadion','1'),
('Gát utca','3'),
('Csallóközi utca','1'),
('Honvéd tér','1'),
('Csillag tér (Lugas utca)','1'),
('Dankó Pista utca','1'),
('Retek utca','1'),
('Hajós utca','1'),
('Etelka sor','1'),
('Gyermekkórház','3'),
('Deli Károly utca','1'),
('Szalámigyár','1'),
('Mars tér (Attila utca)','3'),
('Bajai út','1'),
('Dugonics tér (Petőfi Sándor sugárút)','2'),
('Hargitai utca','1'),
('Erdőstarcsa utca','1'),
('Auchan áruház','1'),
('Közép fasor (Bérkert utca)','1'),
('Klára utca','1'),
('Tűzoltó utca','1'),
('Bakay Nándor utca (Vásárhelyi Pál utca)','3'),
('Csongrádi sugárút (Bercsényi utca)','3'),
('Sajka utca','1'),
('Nagyszombati utca (páratlan oldal)','1'),
('Kereskedő köz','2'),
('Lugas utca','1'),
('Pinty utca','1'),
('Temesvári körút (Népkert sor)','1'),
('Back Bernát utca 2.','1'),
('ELI lézeres kutatóközpont','1'),
('Szúnyog utca','1'),
('Glattfelder Gyula tér','3'),
('Hajnal utca','1'),
('Újszeged, víztorony','1'),
('Acél utca','1'),
('Makkosházi körút','1'),
('Szélső sor','1'),
('Széchenyi tér','1'),
('Belvárosi temető II. kapu','2'),
('Apály utca','1'),
('Budapesti körút (József Attila sugárút)','1'),
('Mars tér (Szent Rókus tér)','1'),
('Erdő utca','1'),
('Nagyszombati utca (páros oldal)','1'),
('Rózsatő utca (Szerb utca)','1'),
('Gábor Áron utca','1'),
('Közép fasor','1'),
('Kolozsvári tér','1'),
('Cinke utca','1'),
('Krematórium','1'),
('Szivárvány kitérő','2'),
('Anna-kút (Tisza Lajos körút)','2'),
('Rózsatő utca (Magyar utca)','1'),
('Koszorú utca','1'),
('Fecske utca','3'),
('Strandfürdő','2'),
('Attila utca (Mars tér)','3'),
('Szőreg, malom','1'),
('Budapesti körút','1'),
('Szalámigyár','2'),
('Cincér utca','1'),
('Gólya utca','1'),
('Vadaspark (Textilgyári út)','1'),
('Rókusi víztorony','2'),
('Kálvária tér','2'),
('Tarján, Víztorony tér','1'),
('Gém utca','3'),
('Csillag tér (Budapesti körút)','3'),
('Kecskés','2'),
('Tündér utca','3'),
('Bécsi körút','2'),
('Londoni körút','2'),
('Szatymazi utca','2'),
('Sportcsarnok (Temesvári körút)','1'),
('Czékus utca','1'),
('Balatoni utca','1');