INSERT INTO megallo (cim, megallonev) VALUES
('Iparváros, Tűzoltó utca','Tűzoltó utca'),
('Béketelep, Liliom lakókert, Régi posta út, Nagyszombati utca (páros oldal)','Nagyszombati utca (páros oldal)'),
('Móraváros, Petőfi Sándor sugárút, Szivárvány kitérő','Szivárvány kitérő'),
('Belváros, Attila utca, Attila utca (Mars tér)','Attila utca (Mars tér)'),
('Móraváros, Katona József utca, Alkony utca','Alkony utca'),
('Belváros, Boldogasszony sugárút, Galamb utca','Galamb utca'),
('Belváros, Attila utca, Bartók tér','Bartók tér'),
('Béketelep, Liliom lakókert, Csallóközi utca','Csallóközi utca'),
('Felsőváros, Tömörkény-üdülőtelep, Felső Tisza part, Városi stadion','Városi stadion'),
('Felsőváros, Etelka sor','Etelka sor'),
('Újszeged, Hársfa lakópark, Derkovits fasor, Diófa utca (Derkovits fasor)','Diófa utca (Derkovits fasor)'),
('Iparváros, Kollégiumi út, Dorozsmai út (Kollégiumi út)','Dorozsmai út (Kollégiumi út)'),
('Béketelep, Napos út, Napos út (Dorozsmai út)','Napos út (Dorozsmai út)'),
('Fodorkert, Gedó, József Attila sugárút, Budapesti körút','Budapesti körút'),
('Alsóváros, Szabadság tér','Szabadság tér'),
('Iparváros, Bakay Nándor utca','Bakay Nándor utca'),
('Belváros, Kálvin tér, Anna-kút (Kálvin tér)','Anna-kút (Kálvin tér)'),
('Újrókus, Harmónia lakópark, Rókusi körút, Szatymazi utca','Szatymazi utca'),
('Makkosház, Harmónia lakópark, Csongrádi sugárút, Ipoly sor','Ipoly sor'),
('Odessza, 43303, Gyermekkórház','Gyermekkórház'),
('Szegedi Ipari Logisztikai Központ, Back Bernát utca, Back Bernát utca 2.','Back Bernát utca 2.'),
('Magyarország, 6800, Alföld és Észak, Dél-Alföld, Csongrád-Csanád megye, Hódmezővásárhelyi járás, Hódmezővásárhely, Kertváros, Ady Endre utca, Strandfürdő','Strandfürdő'),
('Tarján, Nagyszilléri domb, Lidicei tér','Lidicei tér'),
('Iparváros, Budapesti út, Budapesti út (Dorozsmai út)','Budapesti út (Dorozsmai út)'),
('Rókus, Vásárhelyi Pál utca','Vásárhelyi Pál utca'),
('Alsóváros, Vadaspark lakópark, Cserepes sor','Cserepes sor'),
('Kecskés István-telep, Vadaspark lakópark, Szabadkai út, Gera Sándor utca, Kecskéstelep','Kecskéstelep, Gera Sándor utca'),
('Móraváros, Vásárhelyi Pál utca, Kálvária sugárút (Vásárhelyi Pál utca)','Kálvária sugárút (Vásárhelyi Pál utca)'),
('Rókus, Franciahögy lakópark, Párizsi körút, Hétvezér utca','Hétvezér utca'),
('Újszeged, Hársfa lakópark, Szőregi út, Aranyosi utca','Aranyosi utca'),
('Felsőváros, Római körút, Gál utca','Gál utca'),
('Klebelsbergtelep, Vaskapu utca, Holt-Tisza','Holt-Tisza'),
('Északi városrész, Gedó, Csongrádi sugárút, Rózsa utca (Csongrádi sugárút)','Rózsa utca (Csongrádi sugárút)'),
('Belváros, Szentháromság utca, Ságvári Gimnázium - SZTK','Ságvári Gimnázium - SZTK'),
('Tápé, Honfoglalás utca, Csatár utca','Csatár utca'),
('Tompasziget, Gyálai út, Cincér utca','Cincér utca'),
('Móraváros, Petőfi Sándor sugárút, Moszkvai körút','Moszkvai körút'),
('Odessza, Derkovits fasor, Kisstadion','Kisstadion'),
('Tarján, Gedó, József Attila sugárút, Retek utca','Retek utca'),
('Kiskundorozsma, Negyvennyolcas utca','Negyvennyolcas utca'),
('Belváros, Tisza Lajos körút, Honvéd tér (Tisza Lajos körút)','Honvéd tér (Tisza Lajos körút)'),
('Újrókus, Vértói út','Vértói út'),
('Móraváros, Moszkvai körút, Kálvária sugárút','Kálvária sugárút'),
('Fodorkert, Gedó, József Attila sugárút, Deák Ferenc Gimnázium','Deák Ferenc Gimnázium'),
('Tarján, Gedó, Retek utca, Szamos utca','Szamos utca'),
('Marostő, Hársfa lakópark, Thököly utca, Traktor utca','Traktor utca'),
('Belváros, Szent István tér','Szent István tér'),
('Újszőreg, Makai út, Barázda utca','Barázda utca'),
('Belváros, Tisza Lajos körút, Déli Klinikai Tömb','Klinikák'),
('Szőreg, Szerb utca, Gyár utca (Szerb utca)','Gyár utca (Szerb utca)'),
('Petőfitelep, Fő tér, Fő tér, Petőfitelep','Petőfitelep, Fő tér'),
('Béketelep, Liliom lakókert, Zsámbokréti sor','Zsámbokréti sor'),
('Újszeged, Bérkert utca, Szöri utca','Szöri utca'),
('Alsóváros, Vadkerti tér','Vadkerti tér'),
('Alsóváros, Vadaspark lakópark, Szabadkai út','Szabadkai út'),
('Iparváros, Fonógyári út, Belvárosi temető','Belvárosi temető'),
('Újrókus, Harmónia lakópark, Rókusi körút, Rókus II. sz. általános iskola','Rókus II. sz. általános iskola'),
('Tarján, Gedó, Rózsa utca, Rózsa utca (József Attila sugárút)','Rózsa utca (József Attila sugárút)'),
('Belváros, Kálvária sugárút, Londoni körút (Kálvária sugárút)','Londoni körút (Kálvária sugárút)'),
('Kiskundorozsma, Széksósi út, Brassói utca','Brassói utca'),
('Belváros, József Attila sugárút, Szent György tér','Szent György tér'),
('Újrókus, Kossuth Lajos sugárút, bejárati út, Szeged-Rókus vasútállomás','Szeged-Rókus vasútállomás, bejárati út'),
('Szőreg, Magyar utca, Vaspálya utca','Vaspálya utca'),
('Kiskundorozsma, Dorozsmai út, Malom (Jerney utca)','Malom (Jerney utca)'),
('Lövölde út, Füvészkert','Füvészkert'),
('Iparváros, Kollégiumi út, Vállalkozó köz','Vállalkozó köz'),
('Kiskundorozsma, Dorozsmai út, ABC, Kiskundorozsma','Kiskundorozsma, ABC'),
('Odessza, Alsó kikötő sor','Alsó kikötő sor'),
('Újpetőfitelep, Nagyszilléri domb, Bánk bán utca, Kalász utca','Kalász utca'),
('Iparváros, Textilgyári út, Vadaspark (Textilgyári út)','Vadaspark (Textilgyári út)'),
('Tompasziget, Gyálai út, Szúnyog utca','Szúnyog utca'),
('Szőreg, Magyar utca, Rózsatő utca (Magyar utca)','Rózsatő utca (Magyar utca)'),
('Budapesti út, Kísérleti gazdaság','Kísérleti gazdaság'),
('Marostői kiskertek, Hősök tere, ABC, Szőreg','Szőreg, ABC'),
('Újszeged, Fő fasor, víztorony, Újszeged','Újszeged, víztorony'),
('Móraváros, Bakay Nándor utca, Mura utca','Mura utca'),
('Iparváros, Tűzoltó utca, Első Szegedi Ipari Park','Első Szegedi Ipari Park'),
('Belváros, Mikszáth Kálmán utca, Mars tér (Mikszáth Kálmán utca)','Mars tér (Mikszáth Kálmán utca)'),
('Petőfitelep, Szántó Kovács János utca, Zágráb utca','Zágráb utca'),
('Iparváros, Fonógyári út, Belvárosi temető II. kapu','Belvárosi temető II. kapu'),
('Móraváros, Katona József utca, Hajnal utca','Hajnal utca'),
('Alsóváros, Vadaspark lakópark, Szabadkai út, Szalámigyár','Szalámigyár'),
('Baktó, Völgyérhát utca','Völgyérhát utca'),
('Újrókus, Harmónia lakópark, Rókusi körút, Rókusi víztorony','Rókusi víztorony'),
('Béketelep, Liliom lakókert, Nagyszombati utca, Rengey utca','Rengey utca'),
('Cserőke, Katalin utca','Katalin utca'),
('Felsőváros, Brüsszeli körút, Sándor utca','Sándor utca'),
('Petőfitelep, Tömörkény-üdülőtelep, Irinyi János utca, Duna utca','Duna utca'),
('Északi városrész, Franciahögy lakópark, Csongrádi sugárút, Gém utca','Gém utca'),
('Tarján, Gedó, Víztorony tér, Víztorony tér, Tarján','Tarján, Víztorony tér'),
('Belváros, Dózsa utca','Dózsa utca'),
('Kiskundorozsma, Dorozsmai út, Csatorna','Csatorna'),
('Belváros, Híd utca, Széchenyi tér','Széchenyi tér'),
('Rókus, Vásárhelyi Pál utca, Csemegi-tó','Csemegi-tó'),
('Szentmihály, Szabadkai út, Szegedi Olimpiai Központ','Szegedi Olimpiai Központ'),
('Belváros, Tisza Lajos körút, Dugonics tér (Tisza Lajos körút)','Dugonics tér (Tisza Lajos körút)'),
('Újrókus, Harmónia lakópark, Körtöltés utca','Körtöltés utca'),
('Északi városrész, Franciahögy lakópark, Csongrádi sugárút, Tündér utca','Tündér utca'),
('Móraváros, Gólya utca, Kolozsvári tér','Kolozsvári tér'),
('Kiskundorozsma, Czékus utca','Czékus utca'),
('Petőfitelep, Szántó Kovács János utca, Fő tér, Petőfitelep','Petőfitelep, Fő tér'),
('Budapesti út, Gumigyár (Budapesti út)','Gumigyár (Budapesti út)'),
('Felsőváros, Római körút, Sajka utca','Sajka utca'),
('Tarján, Gedó, József Attila sugárút, Tarján','Tarján'),
('Újrókus, Rókusi körút, Kisteleki utca','Kisteleki utca'),
('Gyálarét, Gyálaréti út, Apály utca','Apály utca'),
('Béketelep, Napos út, Cserje sor','Cserje sor'),
('Rókus, Vásárhelyi Pál utca, Vásárhelyi Pál utca (Pulcz utca)','Vásárhelyi Pál utca (Pulcz utca)'),
('Alsóváros, Rákóczi utca, Rákóczi utca (Vám tér)','Rákóczi utca (Vám tér)'),
('Újszőreg, Kállayliget, Makai út, Kamaratöltés','Kamaratöltés'),
('Odessza, Temesvári körút, Sportcsarnok (Temesvári körút)','Sportcsarnok (Temesvári körút)'),
('Iparváros, Dorozsmai út, Fonógyári út','Fonógyári út'),
('Kiskundorozsma, Czékus utca, Erdőstarcsa utca','Erdőstarcsa utca'),
('Belváros, Kálvária sugárút, Dugonics tér (Dáni utca)','Dugonics tér (Dáni utca)'),
('Kiskundorozsma, Dobos utca, Huszka Jenő utca','Huszka Jenő utca'),
('Móraváros, Kenyérgyári út, Kenyérgyári út 5.','Kenyérgyári út 5.'),
('Gyálarét, Gyálaréti kiskertek, Koszorú utca, Gyálarét','Gyálarét'),
('Iparváros, Bajai út','Bajai út'),
('Odessza, Temesvári körút, Fő fasor (Temesvári körút)','Fő fasor (Temesvári körút)'),
('Makkosház, Gedó, Ortutay utca, Gát utca','Gát utca'),
('Újszeged, Temesvári körút, Szent-Györgyi Albert utca','Szent-Györgyi Albert utca'),
('Felsőváros, József Attila sugárút, Brüsszeli körút','Brüsszeli körút'),
('Alsóváros, Hattyas utca, Szabad sajtó utca','Szabad sajtó utca'),
('Szőreg, Szerb utca, Szőregi szabadidőpark','Szőregi szabadidőpark'),
('Fodorkert, Gedó, Makkosházi körút, Agyagos utca','Agyagos utca'),
('Iparváros, Dorozsmai út, Budapesti út','Budapesti út'),
('Iparváros, Kereskedő köz, Kereskedő köz (EXPO)','Kereskedő köz (EXPO)'),
('Rókus, Mars tér, Mars tér (üzletsor)','Mars tér (üzletsor)'),
('Felsőváros, Szilléri sugárút, Fecske utca','Fecske utca'),
('Rókus, Harmónia lakópark, Kossuth Lajos sugárút, Vásárhelyi Pál utca','Vásárhelyi Pál utca'),
('Móraváros, Kálvária sugárút, Veres ács utca','Veres ács utca'),
('Alsóváros, Szabadkai út','Szabadkai út'),
('Szőreg, Szerb utca, malom, Szőreg','Szőreg, malom'),
('Odessza, Torontál tér, Torontál tér (P+R)','Torontál tér (P+R)'),
('Magyarország, 6750, Alföld és Észak, Dél-Alföld, Csongrád-Csanád megye, Szegedi járás, Algyő, Tanya utca, Algyő','Algyő'),
('Móraváros, Kálvária sugárút, Kálvária tér','Kálvária tér'),
('Marostő, Hársfa lakópark, Hargitai utca, Pinty utca','Pinty utca'),
('Belváros, Aradi vértanúk tere','Aradi vértanúk tere'),
('Móraváros, Kálvária sugárút, Londoni körút','Londoni körút'),
('Tarján, Gedó, József Attila sugárút, Kecskeméti utca','Kecskeméti utca'),
('Iparváros, Zápor út, Auchan parkoló','Auchan áruház'),
('Tarján, Gedó, Budapesti körút, Csillag tér (Budapesti körút)','Csillag tér (Budapesti körút)'),
('Béketelep, Pulz utca, Rókus vasútállomás','Rókus vasútállomás'),
('Felsőváros, Lugas utca, Csillag tér (Lugas utca)','Csillag tér (Lugas utca)'),
('Rókus, Pulz utca','Pulz utca'),
('Gyálarét, Gyálaréti út, Deli Károly utca','Deli Károly utca'),
('Belváros, Tisza Lajos körút, Glattfelder Gyula tér','Glattfelder Gyula tér'),
('Tápé, Budai Nagy Antal utca, Árok utca','Árok utca'),
('Tompasziget, Gyálai út, Tücsök utca','Tücsök utca'),
('Felsőváros, Kereszttöltés utca, Csaba utca','Csaba utca'),
('Klebelsbergtelep, Ballagitó, Pancsovai utca, Kamarási utca','Kamarási utca'),
('Iparváros, Dorozsmai út, Tassi ház','Tassi ház'),
('Belváros, Tisza Lajos körút, Anna-kút (Tisza Lajos körút)','Anna-kút (Tisza Lajos körút)'),
('Újszőreg, Kállayliget, Makai út, Kavics utca','Kavics utca'),
('Szentmihály, Bodom, Kapisztrán út, Gárdonyi Géza utca','Gárdonyi Géza utca'),
('Kiskundorozsma, Széchenyi István utca, Basahíd utca','Basahíd utca'),
('Nádvágó út, Fehértói halgazdaság','Fehértói halgazdaság'),
('Odessza, Székely sor, Torontál tér (P+R)','Torontál tér (P+R)'),
('Móraváros, Bécsi körút, Petőfi Sándor sugárút','Petőfi Sándor sugárút'),
('Szentmihály, Kapisztrán út, Verbéna utca','Verbéna utca'),
('Magyarország, 6800, Alföld és Észak, Dél-Alföld, Csongrád-Csanád megye, Hódmezővásárhelyi járás, Hódmezővásárhely, Susán, Vízház utca, Hódmezővásárhely vasútállomás','Hódmezővásárhely vasútállomás'),
('Iparváros, Fonógyári út, Ikarusz köz','Ikarusz köz'),
('Újrókus, Rókusi körút, Szatymazi utca','Szatymazi utca'),
('Rókus, Franciahögy lakópark, Kossuth Lajos sugárút, Rókusi templom','Rókusi templom'),
('Kiskundorozsma, Szent János tér','Szent János tér'),
('Felsőváros, Brüsszeli körút','Brüsszeli körút'),
('Móraváros, Kálvária sugárút, II. Kórház','II. Kórház'),
('Odessza, Csanádi utca','Csanádi utca'),
('Belváros, Tisza Lajos körút, Centrum Áruház','Centrum Áruház'),
('Marostő, Hársfa lakópark, Fő fasor, Radnóti utca','Radnóti utca'),
('Iparváros, Kálvária sugárút, Vadaspark','Vadaspark'),
('Klebelsbergtelep, Rendező tér','Rendező tér'),
('Móraváros, Petőfi Sándor sugárút, Vitéz utca','Vitéz utca'),
('Móraváros, Bakay Nándor utca, Londoni körút (Bakay Nándor utca)','Londoni körút (Bakay Nándor utca)'),
('Szentmihály, Bodom, Kapisztrán út, malom, Szentmihály','Szentmihály, malom'),
('Északi városrész, Harmónia lakópark, Rókusi körút, Vértó','Vértó'),
('Magyarország, 6800, Alföld és Észak, Dél-Alföld, Csongrád-Csanád megye, Hódmezővásárhelyi járás, Hódmezővásárhely, Belváros, Andrássy út, Kossuth tér','Kossuth tér'),
('Újszeged, Bérkert utca, Közép fasor (Bérkert utca)','Közép fasor (Bérkert utca)'),
('Iparváros, Bajai út, Repülőtér bejárati út','Repülőtér bejárati út'),
('Kiskundorozsma, Kút utca, Széchenyi István utca','Széchenyi István utca'),
('Belváros, Kossuth Lajos sugárút, Anna-kút (Kossuth Lajos sugárút)','Anna-kút (Kossuth Lajos sugárút)'),
('Iparváros, Dorozsmai út, Kollégiumi út','Kollégiumi út'),
('Északi városrész, Franciahögy lakópark, Csongrádi sugárút, Rózsa utca (Csongrádi sugárút)','Rózsa utca (Csongrádi sugárút)'),
('Iparváros, Fonógyári út, Fonógyári úti iparváros','Fonógyári úti iparváros'),
('Makkosház, Harmónia lakópark, Csongrádi sugárút, Európa liget','Európa liget'),
('Subasa, Széksósi út, Csipkebogyó utca, Subasa','Subasa, Csipkebogyó utca'),
('Újszeged, Töltés utca, víztorony, Újszeged','Újszeged, víztorony'),
('Iparváros, Kereskedő köz, Kereskedelmi raktárak','Kereskedelmi raktárak'),
('Iparváros, Bajai út, Repülőtér','Repülőtér'),
('Újszeged, Fő fasor','Fő fasor'),
('Odessza, Kállayliget, Szőregi út, Diófa utca (Szőregi út)','Diófa utca (Szőregi út)'),
('Belváros, Ady tér, Vitéz utca','Vitéz utca'),
('Belváros, Dugonics tér, Dugonics tér (Kálvária sugárút)','Dugonics tér (Kálvária sugárút)'),
('Alsóváros, Szentháromság utca, Bécsi körút','Bécsi körút'),
('Móraváros, Kálvária sugárút, Földhivatal','Földhivatal'),
('Alsóváros, Indóház tér, Szeged vasútállomás','Szeged vasútállomás'),
('Baktó, Alkotmány utca, Bognár utca','Bognár utca'),
('Fodorkert, Gedó, Budapesti körút, Budapesti körút (József Attila sugárút)','Budapesti körút (József Attila sugárút)'),
('Belváros, Petőfi Sándor sugárút, Földváry utca','Földváry utca'),
('Tápé, Árvácska utca, általános iskola, Tápé','Tápé, általános iskola'),
('Odessza, Vedres utca, Torontál tér (P+R)','Torontál tér (P+R)'),
('Alsóváros, Tompai kapu út, buszforduló, Vadkerti tér','Vadkerti tér, buszforduló'),
('Kiskundorozsma, Jerney utca, Malom (Jerney utca)','Malom (Jerney utca)'),
('Alsóváros, Sárkány utca','Sárkány utca'),
('Rókus, Franciahögy lakópark, Kossuth Lajos sugárút, Tavasz utca','Tavasz utca'),
('Rókus, Rókusi körút, Vásárhelyi Pál utca','Vásárhelyi Pál utca'),
('Móraváros, Vásárhelyi Pál utca, Kenyérgyári út','Kenyérgyári út'),
('Iparváros, Bajai út, Krematórium','Krematórium'),
('Odessza, Lövölde út, Akácfa utca','Akácfa utca'),
('Felsőváros, Római körút, Római körút (Szilléri sugárút)','Római körút (Szilléri sugárút)'),
('Béketelep, Pulz utca, Szeged Plaza','Szeged Plaza'),
('Újszőreg, Kállayliget, Makai út, Napfény köz','Napfény köz'),
('Marostő, Hársfa lakópark, Tanács utca','Tanács utca'),
('Back Bernát utca, Szegedi Ipari Logisztikai Központ','Szegedi Ipari Logisztikai Központ'),
('Felsőváros, Tömörkény-üdülőtelep, Felső Tisza part, Etelka sor','Etelka sor'),
('Móraváros, Bakay Nándor utca, Huszár utca','Huszár utca'),
('Iparváros, Fonógyári út, Kereskedő köz','Kereskedő köz'),
('Kiskundorozsma, Széksósi út','Széksósi út'),
('Alsóváros, Vám tér','Vám tér'),
('Szentmihály, Bodom, Kapisztrán út, Artézi kút','Artézi kút'),
('Alsóváros, Csonka utca','Csonka utca'),
('Újpetőfitelep, Nagyszilléri domb, Végvári utca, Acél utca','Acél utca'),
('Belváros, József Attila sugárút, Lengyel utca','Lengyel utca'),
('Béketelep, Liliom lakókert, Régi posta út, Nagyszombati utca (páratlan oldal)','Nagyszombati utca (páratlan oldal)'),
('Belváros, Tisza Lajos körút, Tisza Lajos körút (Károlyi utca)','Tisza Lajos körút (Károlyi utca)'),
('Újpetőfitelep, Nagyszilléri domb, Algyői út, Diadal utca','Diadal utca'),
('Subasa, Széksósi út, Subasa, Szeged','Szeged, Subasa'),
('Móraváros, Bakay Nándor utca, Bakay Nándor utca (Vásárhelyi Pál utca)','Bakay Nándor utca (Vásárhelyi Pál utca)'),
('Iparváros, Budapesti út, Zápor út','Zápor út'),
('Kecskés István-telep, Vadaspark lakópark, Szabadkai út, Kecskés','Kecskés'),
('Marostő, Hársfa lakópark, Fülemüle utca, Pipiske utca','Pipiske utca'),
('Iparváros, Dorozsmai út, Kiskundorozsma vasútállomás','Kiskundorozsma vasútállomás'),
('Wolfgang Sandner utca, ELI lézeres kutatóközpont','ELI lézeres kutatóközpont'),
('Odessza, Népkert sor, Temesvári körút (Népkert sor)','Temesvári körút (Népkert sor)'),
('Belváros, Boldogasszony sugárút, Bécsi körút','Bécsi körút'),
('Marostő, Hársfa lakópark, Hargitai utca','Hargitai utca'),
('Rókus, Franciahögy lakópark, Kossuth Lajos sugárút, Damjanich utca','Damjanich utca'),
('Újszeged, Bérkert utca, Marostői utca','Marostői utca'),
('Béketelep, Napos út, Béketelepi Általános Iskola','Béketelepi Általános Iskola'),
('Szegedi Ipari Logisztikai Központ, Back Bernát utca, Back Bernát utca 6.','Back Bernát utca 6.'),
('Felsőváros, Felső Tisza part, Tabán utca (Felső Tisza-part)','Tabán utca (Felső Tisza-part)'),
('Alsóváros, Petőfi Sándor sugárút, Rákóczi utca (Vám tér)','Rákóczi utca (Vám tér)'),
('Kiskundorozsma, Kettőshatári út, vásártér, Kiskundorozsma','Kiskundorozsma, vásártér'),
('Felsőváros, Gyík utca, Lugas utca','Lugas utca'),
('Tápé, Tömörkény-üdülőtelep, Bencfahát utca, Dráva utca','Dráva utca'),
('Újpetőfitelep, Ladvánszky utca, Alkotmány utca','Alkotmány utca'),
('Budapesti út, buszforduló, Gumigyár','Gumigyár, buszforduló'),
('Újszeged, Hársfa lakópark, Derkovits fasor, Töltés utca','Töltés utca'),
('Alsóváros, Gólya utca','Gólya utca'),
('Makkosház, Gedó, Ortutay utca','Ortutay utca'),
('Kiskundorozsma, Jerney utca, Jerney János Általános Iskola','Jerney János Általános Iskola'),
('Tarján, Gedó, Budapesti körút, víztorony, Tarján','Tarján, víztorony'),
('Rókus, Franciahögy lakópark, Szent Rókus tér, Mars tér (Szent Rókus tér)','Mars tér (Szent Rókus tér)'),
('Odessza, Vedres utca, Gabonakutató','Gabonakutató'),
('Újpetőfitelep, Délceg utca','Délceg utca'),
('Odessza, Alsó kikötő sor, Hatházak','Hatházak'),
('Magyarország, 6800, Alföld és Észak, Dél-Alföld, Csongrád-Csanád megye, Hódmezővásárhelyi járás, Hódmezővásárhely, Kertváros, Kisállomás sor, Hódmezővásárhelyi Népkert vasútállomás','Hódmezővásárhelyi Népkert vasútállomás'),
('Móraváros, Vásárhelyi Pál utca, Volánbusz Zrt.','Volánbusz Zrt.'),
('Felsőváros, Hajós utca','Hajós utca'),
('Gyálarét, Gyálaréti kiskertek, Koszorú utca','Koszorú utca'),
('Móraváros, Vadaspark lakópark, Katona József utca, Cserepes sor (Katona József utca)','Cserepes sor (Katona József utca)'),
('Újszeged, Fő fasor, Közép fasor','Közép fasor'),
('Szőreg, Magyar utca, Gyár utca (Magyar utca)','Gyár utca (Magyar utca)'),
('Szentmihály, Bodom, Harcos utca','Harcos utca'),
('Szőreg, Magyar utca, Iskola utca','Iskola utca'),
('Petőfitelep, Nagyszilléri domb, Csap utca','Csap utca'),
('Makkosház, Gedó, Makkosházi körút','Makkosházi körút'),
('Belváros, Kelemen László utca, Somogyi utca','Somogyi utca'),
('Kecskés István-telep, Terehalmi út, Fehérparti lejáró','Fehérparti lejáró'),
('Makkosház, Gedó, Csongrádi sugárút, Makkosházi körút (Csongrádi sugárút)','Makkosházi körút (Csongrádi sugárút)'),
('Alsóváros, Rákóczi utca, Szent Ferenc utca','Szent Ferenc utca'),
('Tompasziget, Gyálai út, Kiskertek','Kiskertek'),
('Petőfitelep, Nagyszilléri domb, Csap utca, Gábor Áron utca','Gábor Áron utca'),
('Magyarország, 6800, Alföld és Észak, Dél-Alföld, Csongrád-Csanád megye, Hódmezővásárhelyi járás, Hódmezővásárhely, Hódtó, Andrássy út, Kálvin János tér','Kálvin János tér'),
('Belváros, Mikszáth Kálmán utca, Centrum Áruház','Centrum Áruház'),
('Belváros, Stefánia, Múzeum','Múzeum'),
('Tápé, Budai Nagy Antal utca, Rév utca','Rév utca'),
('Odessza, Körsétaút, Napfényfürdő','Napfényfürdő'),
('Belváros, Franciahögy lakópark, Berlini körút','Berlini körút'),
('Magyarország, 6800, Alföld és Észak, Dél-Alföld, Csongrád-Csanád megye, Hódmezővásárhelyi járás, Hódmezővásárhely, Belváros, Tóalj utca, Hősök tere','Hősök tere'),
('Újrókus, Harmónia lakópark, Rókusi körút, Rókusi II. sz. általános iskola','Rókusi II. sz. általános iskola'),
('Belváros, Tisza Lajos körút, Dugonics tér (Petőfi Sándor sugárút)','Dugonics tér (Petőfi Sándor sugárút)'),
('Szőreg, Szerb utca, Rózsatő utca (Szerb utca)','Rózsatő utca (Szerb utca)'),
('Makkosház, Gedó, Hont Ferenc utca, Gát utca','Gát utca'),
('Felsőváros, József Attila sugárút, Dankó Pista utca','Dankó Pista utca'),
('Belváros, Franciahögy lakópark, Csongrádi sugárút, Csongrádi sugárút (Bercsényi utca)','Csongrádi sugárút (Bercsényi utca)'),
('Újpetőfitelep, Délceg utca, Balatoni utca','Balatoni utca'),
('Baktó, Alkotmány utca, Gyümölcs utca','Gyümölcs utca'),
('Kecskés István-telep, Terehalmi út, Bódi Vera utca, Kecskéstelep','Kecskéstelep, Bódi Vera utca'),
('Marostő, Hársfa lakópark, Fő fasor, Cinke utca','Cinke utca'),
('Marostő, Hársfa lakópark, Derkovits fasor','Derkovits fasor'),
('Belváros, Mars tér, Mars tér (autóbusz-állomás)','Mars tér (autóbusz-állomás)'),
('Marostő, Hársfa lakópark, Fő fasor, Thököly utca','Thököly utca'),
('Kiskundorozsma, Negyvennyolcas utca, Balajthy utca','Balajthy utca'),
('Cserőke, Hársfa lakópark, Katalin utca, Klára utca','Klára utca'),
('Tápé, Tömörkény-üdülőtelep, Budai Nagy Antal utca, Beszterce utca','Beszterce utca'),
('Szőreg, Gőzmalom utca','Gőzmalom utca'),
('Szőreg, Szerb utca, Kossuth Lajos Általános Iskola','Kossuth Lajos Általános Iskola'),
('Makkosház, Ipoly sor, Makkosház','Makkosház'),
('Felsőváros, Felső Tisza part, Háló utca','Háló utca'),
('Sziksós, Turista utca, Sziksósfürdő','Sziksósfürdő'),
('Északi városrész, Gedó, Csongrádi sugárút, Diófa Vendéglő','Diófa Vendéglő'),
('Északi városrész, Harmónia lakópark, Rókusi körút, Makkosházi körút (Rókusi körút)','Makkosházi körút (Rókusi körút)'),
('Móraváros, Katona József utca, Szél utca','Szél utca'),
('Újszeged, Bérkert utca, Szövetség utca','Szövetség utca'),
('Alsóváros, Bem utca','Bem utca'),
('Budapesti út, Öthalmi diáklakások','Öthalmi diáklakások'),
('Újpetőfitelep, Nagyszilléri domb, Algyői út, Szélső sor','Szélső sor'),
('Alsóváros, Földmíves utca, Dobó utca','Dobó utca'),
('Szentmihály, Bodom, Kapisztrán út, Koppány köz','Koppány köz'),
('Odessza, Népkert sor, Napfényfürdő','Napfényfürdő'),
('Tarján, Gedó, Retek utca, József Attila sugárút (Retek utca)','József Attila sugárút (Retek utca)'),
('Marostő, Hársfa lakópark, Thököly utca, Erdélyi tér','Erdélyi tér'),
('Iparváros, Kollégiumi út, Fonógyári út (Kollégiumi út)','Fonógyári út (Kollégiumi út)'),
('Belváros, Széchenyi tér','Széchenyi tér'),
('Tápé, Honfoglalás utca','Honfoglalás utca'),
('Belváros, Mars tér, Mars tér (Attila utca)','Mars tér (Attila utca)'),
('Felsőváros, Etelka sor, Erdő utca','Erdő utca'),
('Baktó, Alkotmány utca, Kokárda utca','Kokárda utca'),
('Béketelep, Zsámbokréti sor, MEDIKÉMIA, Béketelep','Béketelep, MEDIKÉMIA'),
('Belváros, Vörösmarty utca, Széchenyi tér (Horváth Mihály utca)','Széchenyi tér (Horváth Mihály utca)'),
('Odessza, Székely sor, Sportcsarnok (Székely sor)','Sportcsarnok (Székely sor)'),
('Iparváros, Fonógyári út','Fonógyári út'),
('Belváros, Földváry utca, Honvéd tér','Honvéd tér'),
('Tápé, Árvácska utca, Nyilassy utca','Nyilassy utca')
ON DUPLICATE KEY UPDATE cim=cim, megallonev=megallonev;